name: Update README with recent activity
on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:  # lets you trigger manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update README with latest activity
        uses: Readme-Workflows/recent-activity@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
